 export default function () {
	return [
		{ id: 11, title: 'Drink One', price: 8.00, image: 'https://www.nkuku.com/Media/Data/K/M/KM34%20-%201.jpg?width=500&height=610&mode=crop', imageMain: 'https://www.nkuku.com/Media/Data/K/M/KM34%20-%201.jpg?width=844&height=1010&mode=crop', color: 'white and black', size: '7 x 16.5cm (dia)', description: 'Whether it’s a morning bowl of cereal or an indulgent pudding, our Ama bowls fit the bill. Their handmade shape is created using traditional techniques indigenous to Vietnam and the splatter finish is created by hand.' },
		{ id: 22, title: 'Drink Two', price: 9.00, image: 'https://www.nkuku.com/Media/Data/A/M/AM30%20-%201.jpg?width=500&height=610&mode=crop', imageMain: 'https://www.nkuku.com/Media/Data/A/M/AM30%20-%201.jpg?width=844&height=1010&mode=crop', color: 'white and black', size: '7 x 16.5cm (dia)', description: 'Whether it’s a morning bowl of cereal or an indulgent pudding, our Ama bowls fit the bill. Their handmade shape is created using traditional techniques indigenous to Vietnam and the splatter finish is created by hand.' },
		{ id: 33, title: 'Drink Three', price: 8.00, image: 'https://www.nkuku.com/Media/Data/D/M/DM01%20-%202.jpg?width=500&height=610&mode=crop', imageMain: 'https://www.nkuku.com/Media/Data/D/M/DM01%20-%202.jpg?width=844&height=1010&mode=crop', color: 'red, yellow, blue, green', size: '7 x 16.5cm (dia)', description: 'Whether it’s a morning bowl of cereal or an indulgent pudding, our Ama bowls fit the bill. Their handmade shape is created using traditional techniques indigenous to Vietnam and the splatter finish is created by hand.' },
		{ id: 44, title: 'Drink Four', price: 10.00, image: 'https://www.nkuku.com/Media/Data/M/J/MJ05%20-%201.jpg?width=500&height=610&mode=crop', imageMain: 'https://www.nkuku.com/Media/Data/M/J/MJ05%20-%201.jpg?width=844&height=1010&mode=crop', color: 'white and terricotta', size: '7 x 16.5cm (dia)', description: 'Whether it’s a morning bowl of cereal or an indulgent pudding, our Ama bowls fit the bill. Their handmade shape is created using traditional techniques indigenous to Vietnam and the splatter finish is created by hand.' },
		{ id: 55, title: 'Drink Five', price: 5.00, image: 'https://www.nkuku.com/Media/Data/D/M/DM02%20-%201.jpg?width=500&height=610&mode=crop', imageMain: 'https://www.nkuku.com/Media/Data/D/M/DM02%20-%201.jpg?width=844&height=610&mode=crop', color: 'blue', size: '7 x 16.5cm (dia)', description: 'Whether it’s a morning bowl of cereal or an indulgent pudding, our Ama bowls fit the bill. Their handmade shape is created using traditional techniques indigenous to Vietnam and the splatter finish is created by hand.' },
		{ id: 66, title: 'Drink Six', price: 5.00, image: 'https://www.nkuku.com/Media/Data/D/M/DM04%20-%201.jpg?width=500&height=610&mode=crop', imageMain: 'https://www.nkuku.com/Media/Data/D/M/DM04%20-%201.jpg?width=844&height=610&mode=crop', color: 'mustard', size: '7 x 16.5cm (dia)', description: 'Whether it’s a morning bowl of cereal or an indulgent pudding, our Ama bowls fit the bill. Their handmade shape is created using traditional techniques indigenous to Vietnam and the splatter finish is created by hand.' },
	]
}