 export default function () {
	return [
		{ id: 1, category: 'eat white black', title: 'AMA BOWL', price: 16.95, image: 'https://www.nkuku.com/Media/Data/A/B/AB59%20-%201.jpg?width=450&height=610&mode=crop', imageMain: 'https://www.nkuku.com/Media/Data/A/B/AB59%20-%201.jpg?width=800&height=1010&mode=crop', color: 'White and Black', size: '7 x 16.5cm (dia)', description: 'Whether it’s a morning bowl of cereal or an indulgent pudding, our Ama bowls fit the bill. Their handmade shape is created using traditional techniques indigenous to Vietnam and the splatter finish is created by hand.' },
		{ id: 2, category: 'eat white black', title: 'Bowl2', price: 16.95, image: 'https://www.nkuku.com/Media/Data/K/P/KP38%20-%201.jpg?width=450&height=610&mode=crop', description: 'One earthware bowl', imageMain: 'https://www.nkuku.com/Media/Data/K/P/KP38%20-%201.jpg?width=800&height1010&mode=crop', color: 'White and Black', size: '7 x 16.5cm (dia)' },
		{ id: 3, category: 'eat white grey', title: 'Bowl2', price: 16.95, image: 'https://www.nkuku.com/Media/Data/D/B/DB37%20-%203.jpg?width=450&height=610&mode=crop', description: 'One earthware bowl', imageMain: 'https://www.nkuku.com/Media/Data/D/B/DB37%20-%203.jpg?width=800&height=1010&mode=crop', color: 'White and Grey', size: '7 x 16.5cm (dia)' },
		{ id: 4, category: 'eat blue', title: 'Bowl3', price: 16.95, image: 'https://www.nkuku.com/Media/Data/D/P/DP09%20-%201.jpg?width=450&height=610&mode=crop', description: 'One earthware bowl', imageMain: 'https://www.nkuku.com/Media/Data/D/P/DP09%20-%201.jpg?width=800&height=1010&mode=crop', color: 'Blue', size: '7 x 16.5cm (dia)' },
		{ id: 5, category: 'eat white blue', title: 'Bowl4', price: 16.95, image: 'https://www.nkuku.com/Media/Data/K/B/KB18%20-%201.jpg?width=450&height=610&mode=crop', description: 'One earthware bowl', imageMain: 'https://www.nkuku.com/Media/Data/K/B/KB18%20-%201.jpg?width=800&height=1010&mode=crop', color: 'White and Blue', size: '7 x 16.5cm (dia)' },
		{ id: 6, category: 'eat white yellow', title: 'Bowl5', price: 16.95, image: 'https://www.nkuku.com/Media/Data/D/B/DB06%20-%201.jpg?width=450&height=610&mode=crop', description: 'One earthware bowl', imageMain: 'https://www.nkuku.com/Media/Data/D/B/DB06%20-%201.jpg?width=800&height=1010&mode=crop', color: 'White and Yellow', size: '7 x 16.5cm (dia)' },
		{ id: 7, category: 'drink white black', title: 'Drink One', price: 8.00, image: 'https://www.nkuku.com/Media/Data/K/M/KM34%20-%201.jpg?width=500&height=610&mode=crop', imageMain: 'https://www.nkuku.com/Media/Data/K/M/KM34%20-%201.jpg?width=844&height=1010&mode=crop', color: 'White and Black', size: '7 x 16.5cm (dia)', description: 'Whether it’s a morning bowl of cereal or an indulgent pudding, our Ama bowls fit the bill. Their handmade shape is created using traditional techniques indigenous to Vietnam and the splatter finish is created by hand.' },
		{ id: 8, category: 'drink white black', title: 'Drink Two', price: 9.00, image: 'https://www.nkuku.com/Media/Data/A/M/AM30%20-%201.jpg?width=500&height=610&mode=crop', imageMain: 'https://www.nkuku.com/Media/Data/A/M/AM30%20-%201.jpg?width=844&height=1010&mode=crop', color: 'White and Black', size: '7 x 16.5cm (dia)', description: 'Whether it’s a morning bowl of cereal or an indulgent pudding, our Ama bowls fit the bill. Their handmade shape is created using traditional techniques indigenous to Vietnam and the splatter finish is created by hand.' },
		{ id: 9, category: 'drink red yellow blue green', title: 'Drink Three', price: 8.00, image: 'https://www.nkuku.com/Media/Data/D/M/DM01%20-%202.jpg?width=500&height=610&mode=crop', imageMain: 'https://www.nkuku.com/Media/Data/D/M/DM01%20-%202.jpg?width=844&height=1010&mode=crop', color: 'Red, Yellow, Blue, Green', size: '7 x 16.5cm (dia)', description: 'Whether it’s a morning bowl of cereal or an indulgent pudding, our Ama bowls fit the bill. Their handmade shape is created using traditional techniques indigenous to Vietnam and the splatter finish is created by hand.' },
		{ id: 10, category: 'drink white terricotta', title: 'Drink Four', price: 10.00, image: 'https://www.nkuku.com/Media/Data/M/J/MJ05%20-%201.jpg?width=500&height=610&mode=crop', imageMain: 'https://www.nkuku.com/Media/Data/M/J/MJ05%20-%201.jpg?width=844&height=1010&mode=crop', color: 'White and Terricotta', size: '7 x 16.5cm (dia)', description: 'Whether it’s a morning bowl of cereal or an indulgent pudding, our Ama bowls fit the bill. Their handmade shape is created using traditional techniques indigenous to Vietnam and the splatter finish is created by hand.' },
		{ id: 11, category: 'drink blue', title: 'Drink Five', price: 5.00, image: 'https://www.nkuku.com/Media/Data/D/M/DM02%20-%201.jpg?width=500&height=610&mode=crop', imageMain: 'https://www.nkuku.com/Media/Data/D/M/DM02%20-%201.jpg?width=844&height=610&mode=crop', color: 'Blue', size: '7 x 16.5cm (dia)', description: 'Whether it’s a morning bowl of cereal or an indulgent pudding, our Ama bowls fit the bill. Their handmade shape is created using traditional techniques indigenous to Vietnam and the splatter finish is created by hand.' },
		{ id: 12, category: 'drink yellow', title: 'Drink Six', price: 5.00, image: 'https://www.nkuku.com/Media/Data/D/M/DM04%20-%201.jpg?width=500&height=610&mode=crop', imageMain: 'https://www.nkuku.com/Media/Data/D/M/DM04%20-%201.jpg?width=844&height=610&mode=crop', color: 'Mustard', size: '7 x 16.5cm (dia)', description: 'Whether it’s a morning bowl of cereal or an indulgent pudding, our Ama bowls fit the bill. Their handmade shape is created using traditional techniques indigenous to Vietnam and the splatter finish is created by hand.' },
		{ id: 13, category: 'decorate white terricotta', title: 'New Jug', price: 15.00, image: 'https://cdn.shopify.com/s/files/1/0231/7021/products/White_Stoneware_Milk_Jug_450x710.jpg?v=1534274529', imageMain: 'https://cdn.shopify.com/s/files/1/0231/7021/products/White_Stoneware_Milk_Jug_810x1010.jpg?v=1534274529', color: 'White and Terricotta', size: '7 x 16.5cm (dia)', description: 'Our Kabar jugs are hand dipped in an eye-catching tan and off white monochrome glaze. They are perfect as breakfast jugs, for serving water and cordials or as striking vases.' },
		{ id: 14, category: 'decorate white black', title: 'Jug 2', price: 15.00, image: 'https://www.nkuku.com/Media/Data/A/J/AJ05%20-%201.jpg?width=450&height=610&mode=crop', description: 'One earthware bowl', imageMain: 'https://www.nkuku.com/Media/Data/A/J/AJ05%20-%201.jpg?width=844&height=1010&mode=crop', color: 'White and Black', size: '7 x 16.5cm (dia)' },
		{ id: 15, category: 'decorate white black', title: 'Jug 3', price: 15.00, image: 'https://www.nkuku.com/Media/Data/K/J/KJ05%20-%201.jpg?width=450&height=610&mode=crop', description: 'One earthware bowl', imageMain: 'https://www.nkuku.com/Media/Data/K/J/KJ05%20-%201.jpg?width=844&height=1010&mode=crop', color: 'White and Black', size: '7 x 16.5cm (dia)' },
		{ id: 16, category: 'decorate blue white', title: 'Jug 4', price: 15.00, image: 'https://www.nkuku.com/Media/Data/K/J/KJ03%20-%201.jpg?width=450&height=610&mode=crop', description: 'One earthware bowl', imageMain: 'https://www.nkuku.com/Media/Data/K/J/KJ03%20-%201.jpg?width=844&height=1010&mode=crop', color: 'Blue and White', size: '7 x 16.5cm (dia)' },
		{ id: 17, category: 'decorate yellow', title: 'Jug 5', price: 15.00, image: 'https://images-na.ssl-images-amazon.com/images/I/51yZcHOKwcL._SY450_.jpg', description: 'One earthware bowl', imageMain: 'https://images-na.ssl-images-amazon.com/images/I/51yZcHOKwcL._SY450_.jpg', color: 'Yellow', size: '7 x 16.5cm (dia)' },
		{ id: 18, category: 'decorate grey white', title: 'Jug 6', price: 15.00, image: 'https://www.scandinavianshop.co.uk/img/product//rikki-tikki-just-retro-ceramic-vase-white-3009925-0-1429712686000.jpg', description: 'One earthware bowl', imageMain: 'https://www.scandinavianshop.co.uk/img/product//rikki-tikki-just-retro-ceramic-vase-white-3009925-0-1429712686000.jpg', color: 'Grey and White', size: '7 x 16.5cm (dia)' },
	]
}